#!/usr/bin/env bash
# configures a brand new Ubuntu machine
# update and install nginx
apt-get update -y
apt-get install -y nginx

#setup a html page for nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# nginx config
echo "server {
        listen 80;
        listen [::]:80;
        root /etc/nginx/html;
        index index.html;
        add_header X-Served-By $HOSTNAME;
        }" > /etc/nginx/sites-available/default

# restart the server
service nginx restart

