#!/usr/bin/env bash
# script that doubles the number of webservers and adds new configs

# install nginx
apt-get  update ; apt-get -y install nginx
sudo sed -i '/http {/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
# restart nginx
sudo service nginx restart
